#!/usr/bin/env bash
# Fetches the Lean Kernel Arena's static (hand-crafted) adversarial test files
# into tests/arena/. These are the corner-case soundness tests stored directly
# in the lean-kernel-arena repository; module-based tests (tutorial/*, std,
# mathlib, ...) are generated by the Arena's CI from a Lean toolchain instead —
# see HOWTO-ARENA.md for how to obtain those.
#
# The test list is discovered from the GitHub API rather than hardcoded: the
# Arena adds static tests over time (it went 5 -> 10 -> 12 during development),
# and a hardcoded list silently stops covering the new ones. Each .ndjson has a
# sibling .yaml whose `outcome:` field is the expected verdict — test/run.js
# reads it, so we must never guess the verdict ourselves.
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p tests/arena
API="https://api.github.com/repos/leanprover/lean-kernel-arena/contents/tests"
BASE="https://raw.githubusercontent.com/leanprover/lean-kernel-arena/master/tests"

tests=$(curl -fsSL ${GITHUB_TOKEN:+-H "Authorization: Bearer $GITHUB_TOKEN"} "$API" \
        | sed -n 's/.*"name": *"\(.*\)\.ndjson".*/\1/p' | sort)
if [ -z "$tests" ]; then
  echo "error: could not enumerate tests from $API (rate limited? set GITHUB_TOKEN)" >&2
  exit 1
fi

n=0
for t in $tests; do
  echo "fetching $t"
  curl -fsSL "$BASE/$t.ndjson" -o "tests/arena/$t.ndjson"
  curl -fsSL "$BASE/$t.yaml"   -o "tests/arena/$t.yaml"
  n=$((n + 1))
done
echo "done: $n static tests in tests/arena/."
echo "run them with: npm test   (or: node bin/evmlean.js tests/arena/<name>.ndjson)"
