#!/usr/bin/env bash
# Fetches the Lean Kernel Arena's static (hand-crafted) adversarial test files
# into tests/arena/. These are the corner-case soundness tests stored directly
# in the lean-kernel-arena repository; module-based tests (tutorial/*, std,
# mathlib, ...) are generated by the Arena's CI from a Lean toolchain instead —
# see HOWTO-ARENA.md for how to obtain those.
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p tests/arena
BASE="https://raw.githubusercontent.com/leanprover/lean-kernel-arena/master/tests"
for t in constlevels level-imax-leq level-imax-normalization nat-rec-rules large-elim-param; do
  echo "fetching $t.ndjson"
  curl -fsSL "$BASE/$t.ndjson" -o "tests/arena/$t.ndjson"
done
echo "done. run them with: npm test   (or: node bin/evmlean.js tests/arena/<name>.ndjson)"
